<?php
require_once __DIR__ . '/includes/functions.php';
$page_title = 'Explore salons';
$search = trim($_GET['q'] ?? ''); $city = trim($_GET['city'] ?? '');
$where = ["s.status = 'approved' AND EXISTS (SELECT 1 FROM users owner WHERE owner.id=s.vendor_id AND owner.status='active')"]; $params = [];
if ($search !== '') { $where[] = '(s.name LIKE ? OR s.city LIKE ? OR s.address LIKE ? OR EXISTS (SELECT 1 FROM services sx WHERE sx.salon_id = s.id AND sx.status=\'active\' AND sx.name LIKE ?))'; array_push($params, "%$search%", "%$search%", "%$search%", "%$search%"); }
if ($city !== '') { $where[] = 's.city = ?'; $params[] = $city; }
$order = 's.name ASC, s.id ASC';
$sql = "SELECT s.*, (SELECT MIN(price) FROM services WHERE salon_id=s.id AND status='active') starting_price, (SELECT COUNT(*) FROM services WHERE salon_id=s.id AND status='active') service_count FROM salons s WHERE " . implode(' AND ', $where) . " ORDER BY $order";
$stmt = db()->prepare($sql); $stmt->execute($params); $salons = $stmt->fetchAll(); include __DIR__ . '/includes/header.php';
?><header class="page-intro"><div class="container"><div class="section-label">The directory</div><h1 class="display-4">Find your next favourite place.</h1><p class="muted col-lg-6">From a quick clean-up to a full afternoon of self-care, find a salon that gets your point of view.</p></div></header><main class="section-pad"><div class="container"><form class="row g-2 mb-5"><div class="col-md-8"><input class="form-control" name="q" value="<?= e($search) ?>" placeholder="Search salon, service or location..."></div><div class="col-md-3"><select class="form-select" name="city"><option value="">Any city</option><option <?= $city === 'Mumbai' ? 'selected' : '' ?>>Mumbai</option><option <?= $city === 'Delhi' ? 'selected' : '' ?>>Delhi</option></select></div><div class="col-md-1"><button class="btn btn-brand w-100"><i class="bi bi-search"></i></button></div></form><div class="d-flex justify-content-between mb-3"><span class="muted"><?= count($salons) ?> salons found</span><span class="small muted">Approved partners only</span></div><div class="row g-4"><?php foreach ($salons as $salon): ?><div class="col-md-6 col-lg-4"><a class="salon-card d-block h-100" href="<?= e(url('salon.php?slug=' . urlencode($salon['slug']))) ?>"><img class="salon-image" src="<?= e(image_url($salon['image_url'])) ?>" alt="<?= e($salon['name']) ?>"><div class="card-body"><div class="d-flex justify-content-between"><h2 class="h4"><?= e($salon['name']) ?></h2><span><i class="bi bi-star-fill text-warning"></i> <?= e((string)$salon['rating']) ?></span></div><p class="muted"><i class="bi bi-geo-alt me-1"></i><?= e($salon['city']) ?> · <?= e($salon['address']) ?></p><div class="d-flex justify-content-between border-top pt-3 small"><span><?= e($salon['service_count']) ?> services</span><span><strong><?= e(price_label($salon['starting_price'])) ?></strong></span></div></div></a></div><?php endforeach; ?></div><?php if (!$salons): ?><div class="text-center py-5"><h2>No salons matched that search.</h2><p class="muted">Try a different city or search term.</p></div><?php endif; ?></div></main><?php include __DIR__ . '/includes/footer.php'; ?>
