<?php
require_once __DIR__ . '/../includes/auth-check.php'; require_role('admin');
require_once __DIR__ . '/../includes/vendor-service.php';
$actionMessage = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    post_guard();
    try { review_vendor((int)current_user()['id'],(int)($_POST['salon_id']??0),$_POST['decision']??''); flash('success','Partner application reviewed.'); redirect('admin/dashboard.php'); }
    catch (Throwable $error) { $actionMessage=report_error($error); }
}
$users=db()->query("SELECT role,COUNT(*) total FROM users GROUP BY role")->fetchAll(); $pending=db()->query("SELECT s.*,u.name owner_name,u.email FROM salons s JOIN users u ON u.id=s.vendor_id WHERE s.status='pending' ORDER BY s.created_at DESC")->fetchAll(); $revenue=db()->query("SELECT COALESCE(SUM(amount),0) FROM payments WHERE status='paid'")->fetchColumn(); $usersByRole=['customer'=>0,'vendor'=>0]; foreach($users as $row) if(isset($usersByRole[$row['role']])) $usersByRole[$row['role']]=$row['total']; $page_title='Admin dashboard'; include __DIR__.'/../includes/header.php';
?><main class="dashboard-shell"><div class="container"><div class="mb-5"><div class="section-label">Platform control</div><h1 class="display-5">Admin dashboard</h1><p class="muted">Review new partners and keep an eye on the platform.</p></div><?php if($actionMessage): ?><div class="alert alert-danger py-2 small"><?= e($actionMessage) ?></div><?php endif; ?><div class="row g-3 mb-5"><div class="col-md-3"><div class="stat-card"><span class="muted small">Customers</span><div class="stat-number"><?= e($usersByRole['customer']) ?></div></div></div><div class="col-md-3"><div class="stat-card"><span class="muted small">Vendors</span><div class="stat-number"><?= e($usersByRole['vendor']) ?></div></div></div><div class="col-md-3"><div class="stat-card"><span class="muted small">Pending review</span><div class="stat-number"><?= e(count($pending)) ?></div></div></div><div class="col-md-3"><div class="stat-card"><span class="muted small">Net simulated collections</span><div class="stat-number"><?= money($revenue) ?></div></div></div></div><div class="dashboard-card p-3 p-md-4"><div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><div class="section-label">Partner applications</div><a href="<?= e(url('admin/salons.php')) ?>">View all salons <i class="bi bi-arrow-right" aria-hidden="true"></i></a></div><h2 class="h3">Waiting for review</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Salon</th><th>Owner</th><th>City</th><th>Applied</th><th>Action</th></tr></thead><tbody><?php foreach($pending as $item): ?><tr><td><strong><?= e($item['name']) ?></strong></td><td><?= e($item['owner_name']) ?><small class="d-block muted"><?= e($item['email']) ?></small></td><td><?= e($item['city']) ?></td><td><?= date('d M Y',strtotime($item['created_at'])) ?></td><td><form method="post" class="d-flex gap-2"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="salon_id" value="<?= e($item['id']) ?>"><button class="btn btn-sm btn-brand" name="decision" value="approved">Approve</button><button class="btn btn-sm btn-outline-brand" name="decision" value="rejected">Reject</button></form></td></tr><?php endforeach; ?></tbody></table></div><?php if(!$pending): ?><p class="muted mb-0">No applications need your attention.</p><?php endif; ?></div></div></main><?php include __DIR__.'/../includes/footer.php'; ?>
