<?php
require_once __DIR__.'/../includes/booking-service.php'; require_role('admin');
$search=trim($_GET['q']??''); $status=$_GET['status']??''; $page=max(1,(int)($_GET['page']??1)); $offset=($page-1)*20;
$where='1=1'; $params=[];
if($search!=='') { $where.=' AND (s.name LIKE ? OR s.city LIKE ? OR u.name LIKE ? OR u.email LIKE ?)'; $params=array_fill(0,4,'%'.$search.'%'); }
if(in_array($status,['pending','approved','rejected','inactive'],true)) { $where.=' AND s.status=?'; $params[]=$status; }
$total=(int)query("SELECT COUNT(*) FROM salons s JOIN users u ON u.id=s.vendor_id WHERE $where",$params)->fetchColumn();
$salons=query("SELECT s.*,u.name owner_name,u.email owner_email,u.status owner_status,(SELECT COUNT(*) FROM services WHERE salon_id=s.id AND status='active') service_count,(SELECT COUNT(*) FROM staff WHERE salon_id=s.id AND status='active') staff_count FROM salons s JOIN users u ON u.id=s.vendor_id WHERE $where ORDER BY s.created_at DESC,s.id DESC LIMIT 20 OFFSET $offset",$params)->fetchAll();
$detail=null; $id=(int)($_GET['id']??0);
if($id) {
    $detail=query('SELECT s.*,u.name owner_name,u.email owner_email,u.phone owner_phone,u.status owner_status FROM salons s JOIN users u ON u.id=s.vendor_id WHERE s.id=?',[$id])->fetch();
    if(!$detail) { http_response_code(404); exit('Salon not found.'); }
    $services=query('SELECT name,price,duration_minutes,status FROM services WHERE salon_id=? ORDER BY name',[$id])->fetchAll();
    $staff=query('SELECT name,specialization,status FROM staff WHERE salon_id=? ORDER BY name',[$id])->fetchAll();
    $appointments=(int)query('SELECT COUNT(*) FROM appointments WHERE salon_id=?',[$id])->fetchColumn();
}
$page_title='Manage salons'; include __DIR__.'/../includes/header.php';
?>
<main class="dashboard-shell"><div class="container"><div class="page-heading"><div><div class="section-label">Platform directory</div><h1>Manage salons</h1><p class="muted">View partner details, owner accounts, services and staffing.</p></div><a class="btn btn-outline-brand" href="<?= e(url('admin/dashboard.php')) ?>">Review applications</a></div>
<?php if($detail): ?><section class="dashboard-card p-4 mb-4"><div class="d-flex flex-wrap justify-content-between gap-3"><div><h2 class="h3"><?= e($detail['name']) ?></h2><span class="salon-status status-<?= e($detail['status']) ?>"><?= e(ucfirst($detail['status'])) ?></span></div><a href="<?= e(url('admin/salons.php')) ?>">Back to all salons</a></div>
<div class="row g-4 mt-1"><div class="col-md-6"><h3 class="h6">Salon information</h3><p><?= e($detail['address'].', '.$detail['city']) ?><br><?= e($detail['phone']?:'No salon phone') ?></p><p>Daily hours: <?= e(substr($detail['opening_time'],0,5).' – '.substr($detail['closing_time'],0,5)) ?> IST</p><p><?= e($detail['description']) ?></p><p>Total appointments: <strong><?= $appointments ?></strong></p></div><div class="col-md-6"><h3 class="h6">Owner account</h3><p><?= e($detail['owner_name']) ?><br><?= e($detail['owner_email']) ?><br><?= e($detail['owner_phone']?:'No owner phone') ?></p><p>Account: <?= e(ucfirst($detail['owner_status'])) ?><br>Registered: <?= date('d M Y',strtotime($detail['created_at'])) ?></p></div>
<div class="col-md-6"><h3 class="h6">Services (<?= count($services) ?>)</h3><?php foreach($services as $item): ?><div class="border-top py-2"><?= e($item['name']) ?> · <?= money($item['price']) ?> · <?= (int)$item['duration_minutes'] ?> min <small class="d-block muted"><?= e(ucfirst($item['status'])) ?></small></div><?php endforeach; ?><?php if(!$services): ?><p class="muted">No services added.</p><?php endif; ?></div>
<div class="col-md-6"><h3 class="h6">Staff (<?= count($staff) ?>)</h3><?php foreach($staff as $item): ?><div class="border-top py-2"><?= e($item['name']) ?> <small class="d-block muted"><?= e(($item['specialization']?:'Specialist').' · '.$item['status']) ?></small></div><?php endforeach; ?><?php if(!$staff): ?><p class="muted">No staff added.</p><?php endif; ?></div></div></section><?php endif; ?>
<form class="row g-3 mb-4"><div class="col-md-7"><label for="salon-search" class="form-label">Search salons or owners</label><input class="form-control" id="salon-search" name="q" value="<?= e($search) ?>" placeholder="Salon, city, owner or email"></div><div class="col-md-3"><label for="salon-status" class="form-label">Salon status</label><select class="form-select" id="salon-status" name="status"><option value="">All statuses</option><?php foreach(['pending','approved','rejected','inactive'] as $option): ?><option value="<?= $option ?>" <?= $status===$option?'selected':'' ?>><?= ucfirst($option) ?></option><?php endforeach; ?></select></div><div class="col-md-2 align-self-end"><button class="btn btn-brand w-100">Search</button></div></form>
<div class="dashboard-card p-3 p-md-4"><div class="d-flex justify-content-between mb-3"><h2 class="h4 mb-0">All salons</h2><span class="count-chip"><?= $total ?></span></div><div class="table-responsive" tabindex="0" aria-label="Salon directory"><table class="table align-middle"><thead><tr><th>Salon</th><th>Owner</th><th>City</th><th>Services / staff</th><th>Status</th><th>Details</th></tr></thead><tbody>
<?php foreach($salons as $salon): ?><tr><td><strong><?= e($salon['name']) ?></strong><small class="d-block muted"><?= e($salon['phone']) ?></small></td><td><?= e($salon['owner_name']) ?><small class="d-block muted"><?= e($salon['owner_email']) ?></small></td><td><?= e($salon['city']) ?></td><td><?= (int)$salon['service_count'] ?> active services<br><?= (int)$salon['staff_count'] ?> active specialists</td><td><span class="salon-status status-<?= e($salon['status']) ?>"><?= e(ucfirst($salon['status'])) ?></span><small class="d-block muted mt-1">Owner: <?= e($salon['owner_status']) ?></small></td><td><a href="?id=<?= $salon['id'] ?>">View details</a></td></tr><?php endforeach; ?>
<?php if(!$salons): ?><tr><td colspan="6" class="text-center py-5 muted">No salons match your search.</td></tr><?php endif; ?></tbody></table></div>
<nav class="d-flex gap-3 mt-3" aria-label="Salon pages"><?php if($page>1): ?><a href="?<?= e(http_build_query(['page'=>$page-1,'q'=>$search,'status'=>$status])) ?>">Previous</a><?php endif; ?><?php if($offset+20<$total): ?><a href="?<?= e(http_build_query(['page'=>$page+1,'q'=>$search,'status'=>$status])) ?>">Next</a><?php endif; ?></nav></div></div></main>
<?php include __DIR__.'/../includes/footer.php'; ?>
